version: '3.8'

services:
  web_entrypoint:
    build: ./web_entrypoint/
    ports:
      - 5001:5000
    volumes:
      - ./web_entrypoint/src/build/web:/app

  api_app:
    build: ./api_app/
    volumes:
      - ./api_app/app:/app/app
      - ./common:/app/common
    ports:
      - 5002:5000
    depends_on:
      - rabbit
    env_file:
      - config.env

  cache_app:
    build: ./cache_app/
    volumes:
      - ./cache_app/src:/app/src
      - ./common:/app/common
    depends_on:
      - rabbit
      - redis
    env_file:
      - config.env

  core_app:
    build: ./core_app/
    volumes:
      - ./core_app/src:/app/src
      - ./common:/app/common
    depends_on:
      - rabbit
    env_file:
      - config.env

  db_app:
    build: ./db_app/
    volumes:
      - ./db_app/src:/app/src
      - ./common:/app/common
    depends_on:
      - rabbit
      - postgres
    env_file:
      - config.env
  
  rabbit:
    image: rabbitmq:3.7-management
    volumes:
    - ./rabbitmq/etc/:/etc/rabbitmq/
    - ./rabbitmq/data/:/var/lib/rabbitmq/
    - ./rabbitmq/logs/:/var/log/rabbitmq/
    env_file:
      - config.env

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - ./redis/redis_data:/var/lib/redis
    env_file:
      - config.env

  postgres:
    build: ./postgres/
    ports:
      - 5003:5432
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
    env_file:
      - config.env