version: '3.8'

services:
  # web_entrypoint:
  #   build: ./web_entrypoint/
  #   command: gunicorn -b 0.0.0.0:5000 app:app
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 5001:5000

  # login_app:
  #   build: ./login_app/
  #   command: gunicorn -b 0.0.0.0:5001 app:app
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 5002:5000
  #   depends_on:
  #     - db
  
  api_app:
    build: ./api_app/
    command: gunicorn -b 0.0.0.0:5002 app:app
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5003:5000
    # depends_on:
    #   - db_app
    #   - redis

  cache_app:
    build: ./cache_app/
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5004:5000
    # depends_on:
    #   - redis

  # db_app:
  #   build: ./db_app/
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 5005:5000
  #   depends_on:
  #     - db
  #     - redis
  
  rabbit:
    image: rabbitmq:3.7-management
    ports:
        - "5006:5000"
    restart: always

  # db:
  #   image: postgres:12-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=coin_app
  #     - POSTGRES_PASSWORD=qwerty
  #     - POSTGRES_DB=pgdb

  # redis:
  #   image: "redis:alpine"
  #   command: redis-server --requirepass qwerty
  #   ports:
  #     - "5007:5000"

  #   volumes:
  #     - ./redis-data:/var/lib/redis
  #     - ./redis.conf:/usr/local/etc/redis/redis.conf

  #   environment:
  #     - REDIS_REPLICATION_MODE=master

  #   networks:
  #     node_net:
  #       ipv4_address: 172.28.1.4
