version: '3.8'

services:
  # web_entrypoint:
  #   build: ./web_entrypoint/
  #   ports:
  #     - 5001:4040
  
    # cache_app:
    #   build: ./cache_app/
    #   volumes:
    #     - ./cache_app/src:/app/src
    #     - ./common:/app/common
    #   depends_on:
    #     - rabbit
    #     - redis
    #   env_file:
    #     - config.env
  
    # redis:
    #   image: "redis:alpine"
    #   command: redis-server
    #   volumes:
    #     - ./redis/redis_data:/var/lib/redis
    #   env_file:
    #     - config.env

  api_service:
    build: ./api_service/
    volumes:
      - ./api_service/app:/app/app
    ports:
      - 5003:8000
    depends_on:
      - api_db
    env_file:
      - config.env
      - api_db_config.env    
  
  api_db:
    image: postgres
    ports:  # for debug purpuses
      - 5005:5432
    volumes:
      - ./api_db/postgres_data:/var/lib/postgresql/data/
      - ./api_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    env_file:
      - api_db_config.env    
 