version: '3.8'

services:
  # web_entrypoint:
  #   build: ./web_entrypoint/
  #   ports:
  #     - 5001:5000
  #   volumes:
  #     - ./web_entrypoint/src/build/web:/app
  
    # cache_app:
    #   build: ./cache_app/
    #   volumes:
    #     - ./cache_app/src:/app/src
    #     - ./common:/app/common
    #   depends_on:
    #     - rabbit
    #     - redis
    #   env_file:
    #     - config.env
  
    # redis:
    #   image: "redis:alpine"
    #   command: redis-server
    #   volumes:
    #     - ./redis/redis_data:/var/lib/redis
    #   env_file:
    #     - config.env
    
  rabbit:
    image: rabbitmq:3.7-management
    volumes:
    - ./rabbitmq/etc/:/etc/rabbitmq/
    - ./rabbitmq/data/:/var/lib/rabbitmq/
    - ./rabbitmq/logs/:/var/log/rabbitmq/
    env_file:
      - config.env

  api_service:
    build: ./api_service/
    volumes:
      - ./api_service/app:/app/app
      - ./common:/app/common
    ports:
      - 5002:5000
    depends_on:
      - rabbit
    env_file:
      - config.env
      - api_db_config.env
  
  api_db:
    image: postgres
    ports:  # for debug purpuses
      - 5004:5432
    volumes:
      - ./api_db/postgres_data:/var/lib/postgresql/data/
      - ./api_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    env_file:
      - api_db_config.env
      
  account_service:
    build: ./account_service/
    volumes:
      - ./account_service/src:/app/src
      - ./common:/app/common
    depends_on:
      - rabbit
    env_file:
      - config.env
      - account_db_config.env

  account_db:
    image: postgres
    ports: # for debug purpuses
      - 5003:5432
    volumes:
      - ./account_db/postgres_data:/var/lib/postgresql/data/
      - ./account_db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    env_file:
      - account_db_config.env
