version: '3.8'

services:
  # web_entrypoint:
  #   build: ./web_entrypoint/
  #   command: gunicorn -b 0.0.0.0:5000 app:app
  #   volumes:
  #     - ./:/usr/src/app/
  #   ports:
  #     - 5001:5000
  
  api_app:
    build: ./api_app/
    volumes:
      - ./api_app/app:/app/app
    ports:
      - 5003:5000
    depends_on:
      - rabbit
    env_file:
      - config.env

  cache_app:
    build: ./cache_app/
    volumes:
      - ./cache_app/src:/app/src
    depends_on:
      - rabbit
      - redis
    env_file:
      - config.env

  db_app:
    build: ./db_app/
    volumes:
      - ./db_app/src:/app/src
    depends_on:
      - rabbit
      - postgres
    env_file:
      - config.env
  
  rabbit:
    image: rabbitmq:3.7-management
    hostname: "rabbit"
    restart: always
    env_file:
      - config.env

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - ./redis/redis_data:/var/lib/redis
    ports:
      - 5004:6379
    restart: always
    env_file:
      - config.env

  postgres:
    image: postgres:12-alpine
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5005:5432
    env_file:
      - config.env