AMQP_URI: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

LOGGING:
    version: 1
    formatters:
        standart:
            format: '%(asctime)s %(levelname)s: %(message)s'
            datefmt: '%m/%d/%Y %I:%M:%S %p'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: standart
    root:
        level: DEBUG
        handlers: [console]
