AMQP_URI: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}

rpc_exchange: 'nameko-rpc'

LOGGING:
    version: 1
    formatters:
        standart:
            format: '%(asctime)s %(levelname)s: %(message)s'
            datefmt: '%m/%d/%Y %I:%M:%S %p'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: standart
    root:
        level: DEBUG
        handlers: [console]

# REDIS:
#   DEFAULT:
#     url: 'redis://localhost:5007/0'
#     options:
#       retry_on_timeout: True
#       decode_responses: True